---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: task2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: task2-pod
        image: eu.gcr.io/dev-project-302319/app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: task2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: app-cert
spec:
  domains:
    - app.fferauu.tk
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-name
  annotations:
    kubernetes.io/ingress.global-static-ip-name: app-ip
    networking.gke.io/managed-certificates: app-cert
spec:
  backend:
    serviceName: app-service
    servicePort: 8080