steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/dev-project-302319/app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/dev-project-302319/app']
images: ['eu.gcr.io/dev-project-302319/app']